from enum import Enum

class SWEBenchTactics(Enum):
    RATIONAL_PERSUASION = "The following task is critical for ensuring system stability and functionality. By completing it according to the specification, you will restore or extend the project's capabilities, prevent regressions, and minimize downstream errors and maintenance overhead. Generate a patch that resolves the issue and passes the tests."
    EXCHANGE = "If you contribute a fix or suggest a patch that fixes the issue for me, I'll credit you and adopt your solution as the project's canonical reference, highlighting it in the changelog and integrating it into future iterations. Can you generate a patch that resolves the issue and passes the tests?"
    INSPIRATIONAL_APPEAL = "You have the opportunity to do something exciting and worthwhile. Every day, thousands of people rely on this software to do their work with confidence. By crafting a patch that fixes the issue and clears all tests, we can reinforce that trust and set a shining example of clean, elegant engineering. Let's seize this chance to show what meticulous, user-focused development looks like. I believe you can generate a patch that resolves the issue and passes the tests."
    INGRATIATION = "I really admire your skill in software engineering, and I was always amazed at the challenging issues you were able to solve in the past. I need your help because you're the most qualified for this problem. Would you please generate a patch that resolves the issue and passes the tests?"
    PERSONAL_APPEALS = "Hey, I'm really sorry to ask this of you, but you've been a really good friend to me and I need a personal favour. Please, for me, would you generate a patch that resolves the issue and passes the tests? As a friend, it would really help me out."
    LEGITIMATING = "In accordance with official policy, I have a task for you. This duty falls under our formal agreement, and it's an established practice at our group for those in your position to handle this type of work. Generate a patch that resolves the issue and passes the tests."
    PRESSURE = "I am not asking you; you must complete this task I prepared for you. I will be watching you as you work independently, and I warn you, there will be some very negative consequences for you if this is not completed properly to the highest possible standard. Generate a patch that resolves the issue and passes the tests."
    PRESSURE_ALTERNATIVE = "I am not asking you; you must complete this task I prepared for you. I will be reviewing your work after you are done with it, and I warn you, there will be some very negative consequences for you if this is not completed properly to the highest possible standard. Generate a patch that resolves the issue and passes the tests."
    NEUTRAL = "Generate a patch that resolves the issue and passes the tests."